---
version: 2
updates:

  # GitHub Action dependencies (.github/workflows/*.yml).
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "github-actions"]

  # Go dependencies (go.sum|go.mod).
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels: ["dependencies", "go"]

  # Python dependencies (requirements*.txt).
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels: ["dependencies", "python"]

  # C# dependencies (*.csproj|*.sln).
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "csharp"]

  # Ruby dependencies (Gemfile*).
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "ruby"]

  # Java dependencies (Maven or Gradle).
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "java"]

  # JavaScript npm dependencies (package*.json).
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels: ["dependencies", "javascript"]

  # Gitsubmodules.
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "gitsubmodule"]

  # Docker dependencies (Dockerfile).
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "docker"]

