name: 🐛 Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
assignees: ["jcleal"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Make sure there aren't any open/closed issues for this topic.

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Give us a brief description of what happened and what should have happened
    validations:
      required: true
