name: 🧠 Feature Request
description: Request a new feature or enhancement
title: "[FEAT]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please ensure this feature request of enhancement hasn't already been submitted.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What does this feature or enhancement do? Could you give us a brief description of what you'd like?
    validations:
      required: true
